--- 

- name: copy dbscript.j2 in tasks folder
  template:
   src: dbscript.j2
   dest: /home/ubuntu/kk/config-mgt-ansible/roles/mysql/tasks/dbscript.sql
   owner: root
   group: root
   mode: 0777
  delegate_to: localhost 


- name: copy mysqld.cnf in tasks folder
  template:
   src: mysqld.cnf.j2
   dest: /etc/mysql/mysql.conf.d/mysqld.cnf
   owner: root
   group: root
   mode: 0600
#  delegate_to: localhost 


- name: copy showdatabases.j2 in tasks folder 
  copy:
   src: files/showdatabases.yml 
   dest: /home/ubuntu/kk/config-mgt-ansible/roles/mysql/tasks/showdatabases.yml 
   owner: root 
   group: root 
   mode: 0777 
  delegate_to: localhost


- name: show databases 
  command: > 
   mysql --user={{ mysql_user_name }} --password={{ mysql_user_password }} 
   --execute="show databases" 
  register: results 


- name: show results 
  debug: 
   msg={{ results.stdout_lines }}


- name: Create database user with name 'kapil' and password 'kapil' with all database privileges
  mysql_user:
   name: kapil
   password: kapil
   priv: '*.*:ALL,GRANT'
   state: present 


- name: flush privileges
  command: >
   mysql -e "FLUSH PRIVILEGES;" 


- name: check if mysql database 'kapildb' exists
  stat:
   path: /var/lib/mysql/kapildb
  register: results 


- name: login to mysql and run dbscript.sql script
  command: >
    mysql --user=kapil --password=kapil --host=35.171.133.205
    --execute="source /home/ubuntu/kk/config-mgt-ansible/roles/mysql/tasks/dbscript.sql"
  delegate_to: localhost
  when: not results.stat.exists







#- name: Create database user with name 'kapil' and password 'kapil' with all database privileges
#  mysql_user:
#    name: "{{ tooling_db_username }}" password: "{{ tooling_db_password }}" priv: "{{ tooling_db_name }}:ALL" state: present tags: - db_script ignore_errors: true - name: run mysql script shell: sqlcmd -S 35.175.115.183 -U {{ 
#  mysql_user_name }} -P {{ mysql_user_password }} -i /home/ubuntu/kk/config-mgt-ansible/roles/mysql/tasks/dbscript.sql shell: sqlcmd -S 35.175.115.183 -U {{ mysql_user_name }} -P {{ mysql_user_password }} -i 
#  roles/mysql/tasks/dbscript.sql - name: copy dbscript.j2 in tasks folder copy:
#    src: files/dbscript.sql dest: /home/ubuntu/kk/config-mgt-ansible/roles/mysql/tasks/dbscriptsss.sql owner: root group: root mode: 0777 delegate_to: localhost
